# coding: utf-8

"""
    Airbyte Configuration API

    Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Authentication (OSS): * When authenticating to the Configuration API, you must use Basic Authentication by setting the Authentication Header to Basic and base64 encoding the username and password (which are `airbyte` and `password` by default - so base64 encoding `airbyte:password` results in `YWlyYnl0ZTpwYXNzd29yZA==`). So the full header reads `'Authorization': \"Basic YWlyYnl0ZTpwYXNzd29yZA==\"`   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: contact@airbyte.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from airbyte_config_api_client import schemas  # noqa: F401


class AirbyteStreamAndConfiguration(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    each stream is split in two parts; the immutable schema from source and mutable configuration for destination
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def stream() -> typing.Type['AirbyteStream']:
                return AirbyteStream
        
            @staticmethod
            def config() -> typing.Type['AirbyteStreamConfiguration']:
                return AirbyteStreamConfiguration
            __annotations__ = {
                "stream": stream,
                "config": config,
            }
        additional_properties = schemas.NotAnyTypeSchema
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["stream"]) -> 'AirbyteStream': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["config"]) -> 'AirbyteStreamConfiguration': ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["stream"], typing_extensions.Literal["config"], ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["stream"]) -> typing.Union['AirbyteStream', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["config"]) -> typing.Union['AirbyteStreamConfiguration', schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["stream"], typing_extensions.Literal["config"], ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        stream: typing.Union['AirbyteStream', schemas.Unset] = schemas.unset,
        config: typing.Union['AirbyteStreamConfiguration', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'AirbyteStreamAndConfiguration':
        return super().__new__(
            cls,
            *_args,
            stream=stream,
            config=config,
            _configuration=_configuration,
        )

from airbyte_config_api_client.model.airbyte_stream import AirbyteStream
from airbyte_config_api_client.model.airbyte_stream_configuration import AirbyteStreamConfiguration
