# coding: utf-8

"""
    Airbyte Configuration API

    Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Authentication (OSS): * When authenticating to the Configuration API, you must use Basic Authentication by setting the Authentication Header to Basic and base64 encoding the username and password (which are `airbyte` and `password` by default - so base64 encoding `airbyte:password` results in `YWlyYnl0ZTpwYXNzd29yZA==`). So the full header reads `'Authorization': \"Basic YWlyYnl0ZTpwYXNzd29yZA==\"`   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: contact@airbyte.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from airbyte_config_api_client import schemas  # noqa: F401


class AttemptFailureReason(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "timestamp",
        }
        
        class properties:
            timestamp = schemas.Int64Schema
        
            @staticmethod
            def failureOrigin() -> typing.Type['AttemptFailureOrigin']:
                return AttemptFailureOrigin
        
            @staticmethod
            def failureType() -> typing.Type['AttemptFailureType']:
                return AttemptFailureType
            externalMessage = schemas.StrSchema
            internalMessage = schemas.StrSchema
            stacktrace = schemas.StrSchema
            retryable = schemas.BoolSchema
            __annotations__ = {
                "timestamp": timestamp,
                "failureOrigin": failureOrigin,
                "failureType": failureType,
                "externalMessage": externalMessage,
                "internalMessage": internalMessage,
                "stacktrace": stacktrace,
                "retryable": retryable,
            }
    
    timestamp: MetaOapg.properties.timestamp
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["timestamp"]) -> MetaOapg.properties.timestamp: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["failureOrigin"]) -> 'AttemptFailureOrigin': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["failureType"]) -> 'AttemptFailureType': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["externalMessage"]) -> MetaOapg.properties.externalMessage: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["internalMessage"]) -> MetaOapg.properties.internalMessage: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["stacktrace"]) -> MetaOapg.properties.stacktrace: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["retryable"]) -> MetaOapg.properties.retryable: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["timestamp", "failureOrigin", "failureType", "externalMessage", "internalMessage", "stacktrace", "retryable", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["timestamp"]) -> MetaOapg.properties.timestamp: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["failureOrigin"]) -> typing.Union['AttemptFailureOrigin', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["failureType"]) -> typing.Union['AttemptFailureType', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["externalMessage"]) -> typing.Union[MetaOapg.properties.externalMessage, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["internalMessage"]) -> typing.Union[MetaOapg.properties.internalMessage, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["stacktrace"]) -> typing.Union[MetaOapg.properties.stacktrace, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["retryable"]) -> typing.Union[MetaOapg.properties.retryable, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["timestamp", "failureOrigin", "failureType", "externalMessage", "internalMessage", "stacktrace", "retryable", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        timestamp: typing.Union[MetaOapg.properties.timestamp, decimal.Decimal, int, ],
        failureOrigin: typing.Union['AttemptFailureOrigin', schemas.Unset] = schemas.unset,
        failureType: typing.Union['AttemptFailureType', schemas.Unset] = schemas.unset,
        externalMessage: typing.Union[MetaOapg.properties.externalMessage, str, schemas.Unset] = schemas.unset,
        internalMessage: typing.Union[MetaOapg.properties.internalMessage, str, schemas.Unset] = schemas.unset,
        stacktrace: typing.Union[MetaOapg.properties.stacktrace, str, schemas.Unset] = schemas.unset,
        retryable: typing.Union[MetaOapg.properties.retryable, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AttemptFailureReason':
        return super().__new__(
            cls,
            *_args,
            timestamp=timestamp,
            failureOrigin=failureOrigin,
            failureType=failureType,
            externalMessage=externalMessage,
            internalMessage=internalMessage,
            stacktrace=stacktrace,
            retryable=retryable,
            _configuration=_configuration,
            **kwargs,
        )

from airbyte_config_api_client.model.attempt_failure_origin import AttemptFailureOrigin
from airbyte_config_api_client.model.attempt_failure_type import AttemptFailureType
