# coding: utf-8

"""
    Airbyte Configuration API

    Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Authentication (OSS): * When authenticating to the Configuration API, you must use Basic Authentication by setting the Authentication Header to Basic and base64 encoding the username and password (which are `airbyte` and `password` by default - so base64 encoding `airbyte:password` results in `YWlyYnl0ZTpwYXNzd29yZA==`). So the full header reads `'Authorization': \"Basic YWlyYnl0ZTpwYXNzd29yZA==\"`   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: contact@airbyte.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from airbyte_config_api_client import schemas  # noqa: F401


class ConnectionSearch(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            connectionId = schemas.UUIDSchema
            name = schemas.StrSchema
        
            @staticmethod
            def namespaceDefinition() -> typing.Type['NamespaceDefinitionType']:
                return NamespaceDefinitionType
            namespaceFormat = schemas.StrSchema
            prefix = schemas.StrSchema
            sourceId = schemas.UUIDSchema
            destinationId = schemas.UUIDSchema
        
            @staticmethod
            def schedule() -> typing.Type['ConnectionSchedule']:
                return ConnectionSchedule
        
            @staticmethod
            def scheduleType() -> typing.Type['ConnectionScheduleType']:
                return ConnectionScheduleType
        
            @staticmethod
            def scheduleData() -> typing.Type['ConnectionScheduleData']:
                return ConnectionScheduleData
        
            @staticmethod
            def status() -> typing.Type['ConnectionStatus']:
                return ConnectionStatus
        
            @staticmethod
            def source() -> typing.Type['SourceSearch']:
                return SourceSearch
        
            @staticmethod
            def destination() -> typing.Type['DestinationSearch']:
                return DestinationSearch
            __annotations__ = {
                "connectionId": connectionId,
                "name": name,
                "namespaceDefinition": namespaceDefinition,
                "namespaceFormat": namespaceFormat,
                "prefix": prefix,
                "sourceId": sourceId,
                "destinationId": destinationId,
                "schedule": schedule,
                "scheduleType": scheduleType,
                "scheduleData": scheduleData,
                "status": status,
                "source": source,
                "destination": destination,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["connectionId"]) -> MetaOapg.properties.connectionId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["namespaceDefinition"]) -> 'NamespaceDefinitionType': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["namespaceFormat"]) -> MetaOapg.properties.namespaceFormat: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["prefix"]) -> MetaOapg.properties.prefix: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sourceId"]) -> MetaOapg.properties.sourceId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["destinationId"]) -> MetaOapg.properties.destinationId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["schedule"]) -> 'ConnectionSchedule': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["scheduleType"]) -> 'ConnectionScheduleType': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["scheduleData"]) -> 'ConnectionScheduleData': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> 'ConnectionStatus': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["source"]) -> 'SourceSearch': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["destination"]) -> 'DestinationSearch': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["connectionId", "name", "namespaceDefinition", "namespaceFormat", "prefix", "sourceId", "destinationId", "schedule", "scheduleType", "scheduleData", "status", "source", "destination", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["connectionId"]) -> typing.Union[MetaOapg.properties.connectionId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> typing.Union[MetaOapg.properties.name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["namespaceDefinition"]) -> typing.Union['NamespaceDefinitionType', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["namespaceFormat"]) -> typing.Union[MetaOapg.properties.namespaceFormat, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["prefix"]) -> typing.Union[MetaOapg.properties.prefix, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sourceId"]) -> typing.Union[MetaOapg.properties.sourceId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["destinationId"]) -> typing.Union[MetaOapg.properties.destinationId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["schedule"]) -> typing.Union['ConnectionSchedule', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["scheduleType"]) -> typing.Union['ConnectionScheduleType', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["scheduleData"]) -> typing.Union['ConnectionScheduleData', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union['ConnectionStatus', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["source"]) -> typing.Union['SourceSearch', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["destination"]) -> typing.Union['DestinationSearch', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["connectionId", "name", "namespaceDefinition", "namespaceFormat", "prefix", "sourceId", "destinationId", "schedule", "scheduleType", "scheduleData", "status", "source", "destination", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        connectionId: typing.Union[MetaOapg.properties.connectionId, str, uuid.UUID, schemas.Unset] = schemas.unset,
        name: typing.Union[MetaOapg.properties.name, str, schemas.Unset] = schemas.unset,
        namespaceDefinition: typing.Union['NamespaceDefinitionType', schemas.Unset] = schemas.unset,
        namespaceFormat: typing.Union[MetaOapg.properties.namespaceFormat, str, schemas.Unset] = schemas.unset,
        prefix: typing.Union[MetaOapg.properties.prefix, str, schemas.Unset] = schemas.unset,
        sourceId: typing.Union[MetaOapg.properties.sourceId, str, uuid.UUID, schemas.Unset] = schemas.unset,
        destinationId: typing.Union[MetaOapg.properties.destinationId, str, uuid.UUID, schemas.Unset] = schemas.unset,
        schedule: typing.Union['ConnectionSchedule', schemas.Unset] = schemas.unset,
        scheduleType: typing.Union['ConnectionScheduleType', schemas.Unset] = schemas.unset,
        scheduleData: typing.Union['ConnectionScheduleData', schemas.Unset] = schemas.unset,
        status: typing.Union['ConnectionStatus', schemas.Unset] = schemas.unset,
        source: typing.Union['SourceSearch', schemas.Unset] = schemas.unset,
        destination: typing.Union['DestinationSearch', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ConnectionSearch':
        return super().__new__(
            cls,
            *_args,
            connectionId=connectionId,
            name=name,
            namespaceDefinition=namespaceDefinition,
            namespaceFormat=namespaceFormat,
            prefix=prefix,
            sourceId=sourceId,
            destinationId=destinationId,
            schedule=schedule,
            scheduleType=scheduleType,
            scheduleData=scheduleData,
            status=status,
            source=source,
            destination=destination,
            _configuration=_configuration,
            **kwargs,
        )

from airbyte_config_api_client.model.connection_schedule import ConnectionSchedule
from airbyte_config_api_client.model.connection_schedule_data import ConnectionScheduleData
from airbyte_config_api_client.model.connection_schedule_type import ConnectionScheduleType
from airbyte_config_api_client.model.connection_status import ConnectionStatus
from airbyte_config_api_client.model.destination_search import DestinationSearch
from airbyte_config_api_client.model.namespace_definition_type import NamespaceDefinitionType
from airbyte_config_api_client.model.source_search import SourceSearch
