# coding: utf-8

"""
    Airbyte Configuration API

    Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Authentication (OSS): * When authenticating to the Configuration API, you must use Basic Authentication by setting the Authentication Header to Basic and base64 encoding the username and password (which are `airbyte` and `password` by default - so base64 encoding `airbyte:password` results in `YWlyYnl0ZTpwYXNzd29yZA==`). So the full header reads `'Authorization': \"Basic YWlyYnl0ZTpwYXNzd29yZA==\"`   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: contact@airbyte.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from airbyte_config_api_client import schemas  # noqa: F401


class DestinationDefinitionSpecificationRead(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "destinationDefinitionId",
            "jobInfo",
        }
        
        class properties:
            destinationDefinitionId = schemas.UUIDSchema
        
            @staticmethod
            def jobInfo() -> typing.Type['SynchronousJobRead']:
                return SynchronousJobRead
            documentationUrl = schemas.StrSchema
            connectionSpecification = schemas.AnyTypeSchema
        
            @staticmethod
            def authSpecification() -> typing.Type['AuthSpecification']:
                return AuthSpecification
        
            @staticmethod
            def advancedAuth() -> typing.Type['AdvancedAuth']:
                return AdvancedAuth
            
            
            class supportedDestinationSyncModes(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['DestinationSyncMode']:
                        return DestinationSyncMode
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['DestinationSyncMode'], typing.List['DestinationSyncMode']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'supportedDestinationSyncModes':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'DestinationSyncMode':
                    return super().__getitem__(i)
            __annotations__ = {
                "destinationDefinitionId": destinationDefinitionId,
                "jobInfo": jobInfo,
                "documentationUrl": documentationUrl,
                "connectionSpecification": connectionSpecification,
                "authSpecification": authSpecification,
                "advancedAuth": advancedAuth,
                "supportedDestinationSyncModes": supportedDestinationSyncModes,
            }
    
    destinationDefinitionId: MetaOapg.properties.destinationDefinitionId
    jobInfo: 'SynchronousJobRead'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["destinationDefinitionId"]) -> MetaOapg.properties.destinationDefinitionId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["jobInfo"]) -> 'SynchronousJobRead': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["documentationUrl"]) -> MetaOapg.properties.documentationUrl: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["connectionSpecification"]) -> MetaOapg.properties.connectionSpecification: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["authSpecification"]) -> 'AuthSpecification': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["advancedAuth"]) -> 'AdvancedAuth': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["supportedDestinationSyncModes"]) -> MetaOapg.properties.supportedDestinationSyncModes: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["destinationDefinitionId", "jobInfo", "documentationUrl", "connectionSpecification", "authSpecification", "advancedAuth", "supportedDestinationSyncModes", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["destinationDefinitionId"]) -> MetaOapg.properties.destinationDefinitionId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["jobInfo"]) -> 'SynchronousJobRead': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["documentationUrl"]) -> typing.Union[MetaOapg.properties.documentationUrl, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["connectionSpecification"]) -> typing.Union[MetaOapg.properties.connectionSpecification, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["authSpecification"]) -> typing.Union['AuthSpecification', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["advancedAuth"]) -> typing.Union['AdvancedAuth', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["supportedDestinationSyncModes"]) -> typing.Union[MetaOapg.properties.supportedDestinationSyncModes, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["destinationDefinitionId", "jobInfo", "documentationUrl", "connectionSpecification", "authSpecification", "advancedAuth", "supportedDestinationSyncModes", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        destinationDefinitionId: typing.Union[MetaOapg.properties.destinationDefinitionId, str, uuid.UUID, ],
        jobInfo: 'SynchronousJobRead',
        documentationUrl: typing.Union[MetaOapg.properties.documentationUrl, str, schemas.Unset] = schemas.unset,
        connectionSpecification: typing.Union[MetaOapg.properties.connectionSpecification, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        authSpecification: typing.Union['AuthSpecification', schemas.Unset] = schemas.unset,
        advancedAuth: typing.Union['AdvancedAuth', schemas.Unset] = schemas.unset,
        supportedDestinationSyncModes: typing.Union[MetaOapg.properties.supportedDestinationSyncModes, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'DestinationDefinitionSpecificationRead':
        return super().__new__(
            cls,
            *_args,
            destinationDefinitionId=destinationDefinitionId,
            jobInfo=jobInfo,
            documentationUrl=documentationUrl,
            connectionSpecification=connectionSpecification,
            authSpecification=authSpecification,
            advancedAuth=advancedAuth,
            supportedDestinationSyncModes=supportedDestinationSyncModes,
            _configuration=_configuration,
            **kwargs,
        )

from airbyte_config_api_client.model.advanced_auth import AdvancedAuth
from airbyte_config_api_client.model.auth_specification import AuthSpecification
from airbyte_config_api_client.model.destination_sync_mode import DestinationSyncMode
from airbyte_config_api_client.model.synchronous_job_read import SynchronousJobRead
