# coding: utf-8

"""
    Airbyte Configuration API

    Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Authentication (OSS): * When authenticating to the Configuration API, you must use Basic Authentication by setting the Authentication Header to Basic and base64 encoding the username and password (which are `airbyte` and `password` by default - so base64 encoding `airbyte:password` results in `YWlyYnl0ZTpwYXNzd29yZA==`). So the full header reads `'Authorization': \"Basic YWlyYnl0ZTpwYXNzd29yZA==\"`   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: contact@airbyte.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from airbyte_config_api_client import schemas  # noqa: F401


class FieldTransform(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Describes the difference between two Streams.
    """


    class MetaOapg:
        required = {
            "fieldName",
            "transformType",
            "breaking",
        }
        
        class properties:
            
            
            class transformType(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "add_field": "ADD_FIELD",
                        "remove_field": "REMOVE_FIELD",
                        "update_field_schema": "UPDATE_FIELD_SCHEMA",
                    }
                
                @schemas.classproperty
                def ADD_FIELD(cls):
                    return cls("add_field")
                
                @schemas.classproperty
                def REMOVE_FIELD(cls):
                    return cls("remove_field")
                
                @schemas.classproperty
                def UPDATE_FIELD_SCHEMA(cls):
                    return cls("update_field_schema")
        
            @staticmethod
            def fieldName() -> typing.Type['FieldName']:
                return FieldName
            breaking = schemas.BoolSchema
        
            @staticmethod
            def addField() -> typing.Type['FieldAdd']:
                return FieldAdd
        
            @staticmethod
            def removeField() -> typing.Type['FieldRemove']:
                return FieldRemove
        
            @staticmethod
            def updateFieldSchema() -> typing.Type['FieldSchemaUpdate']:
                return FieldSchemaUpdate
            __annotations__ = {
                "transformType": transformType,
                "fieldName": fieldName,
                "breaking": breaking,
                "addField": addField,
                "removeField": removeField,
                "updateFieldSchema": updateFieldSchema,
            }
    
    fieldName: 'FieldName'
    transformType: MetaOapg.properties.transformType
    breaking: MetaOapg.properties.breaking
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["transformType"]) -> MetaOapg.properties.transformType: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fieldName"]) -> 'FieldName': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["breaking"]) -> MetaOapg.properties.breaking: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["addField"]) -> 'FieldAdd': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["removeField"]) -> 'FieldRemove': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["updateFieldSchema"]) -> 'FieldSchemaUpdate': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["transformType", "fieldName", "breaking", "addField", "removeField", "updateFieldSchema", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["transformType"]) -> MetaOapg.properties.transformType: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fieldName"]) -> 'FieldName': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["breaking"]) -> MetaOapg.properties.breaking: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["addField"]) -> typing.Union['FieldAdd', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["removeField"]) -> typing.Union['FieldRemove', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["updateFieldSchema"]) -> typing.Union['FieldSchemaUpdate', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["transformType", "fieldName", "breaking", "addField", "removeField", "updateFieldSchema", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        fieldName: 'FieldName',
        transformType: typing.Union[MetaOapg.properties.transformType, str, ],
        breaking: typing.Union[MetaOapg.properties.breaking, bool, ],
        addField: typing.Union['FieldAdd', schemas.Unset] = schemas.unset,
        removeField: typing.Union['FieldRemove', schemas.Unset] = schemas.unset,
        updateFieldSchema: typing.Union['FieldSchemaUpdate', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'FieldTransform':
        return super().__new__(
            cls,
            *_args,
            fieldName=fieldName,
            transformType=transformType,
            breaking=breaking,
            addField=addField,
            removeField=removeField,
            updateFieldSchema=updateFieldSchema,
            _configuration=_configuration,
            **kwargs,
        )

from airbyte_config_api_client.model.field_add import FieldAdd
from airbyte_config_api_client.model.field_name import FieldName
from airbyte_config_api_client.model.field_remove import FieldRemove
from airbyte_config_api_client.model.field_schema_update import FieldSchemaUpdate
