# coding: utf-8

"""
    Airbyte Configuration API

    Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Authentication (OSS): * When authenticating to the Configuration API, you must use Basic Authentication by setting the Authentication Header to Basic and base64 encoding the username and password (which are `airbyte` and `password` by default - so base64 encoding `airbyte:password` results in `YWlyYnl0ZTpwYXNzd29yZA==`). So the full header reads `'Authorization': \"Basic YWlyYnl0ZTpwYXNzd29yZA==\"`   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: contact@airbyte.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from airbyte_config_api_client import schemas  # noqa: F401


class NormalizationDestinationDefinitionConfig(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    describes a normalization config for destination definition
    """


    class MetaOapg:
        required = {
            "supported",
        }
        
        class properties:
            supported = schemas.BoolSchema
            normalizationRepository = schemas.StrSchema
            normalizationTag = schemas.StrSchema
            normalizationIntegrationType = schemas.StrSchema
            __annotations__ = {
                "supported": supported,
                "normalizationRepository": normalizationRepository,
                "normalizationTag": normalizationTag,
                "normalizationIntegrationType": normalizationIntegrationType,
            }
        additional_properties = schemas.NotAnyTypeSchema
    
    supported: MetaOapg.properties.supported
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["supported"]) -> MetaOapg.properties.supported: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["normalizationRepository"]) -> MetaOapg.properties.normalizationRepository: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["normalizationTag"]) -> MetaOapg.properties.normalizationTag: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["normalizationIntegrationType"]) -> MetaOapg.properties.normalizationIntegrationType: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["supported"], typing_extensions.Literal["normalizationRepository"], typing_extensions.Literal["normalizationTag"], typing_extensions.Literal["normalizationIntegrationType"], ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["supported"]) -> MetaOapg.properties.supported: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["normalizationRepository"]) -> typing.Union[MetaOapg.properties.normalizationRepository, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["normalizationTag"]) -> typing.Union[MetaOapg.properties.normalizationTag, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["normalizationIntegrationType"]) -> typing.Union[MetaOapg.properties.normalizationIntegrationType, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["supported"], typing_extensions.Literal["normalizationRepository"], typing_extensions.Literal["normalizationTag"], typing_extensions.Literal["normalizationIntegrationType"], ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        supported: typing.Union[MetaOapg.properties.supported, bool, ],
        normalizationRepository: typing.Union[MetaOapg.properties.normalizationRepository, str, schemas.Unset] = schemas.unset,
        normalizationTag: typing.Union[MetaOapg.properties.normalizationTag, str, schemas.Unset] = schemas.unset,
        normalizationIntegrationType: typing.Union[MetaOapg.properties.normalizationIntegrationType, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'NormalizationDestinationDefinitionConfig':
        return super().__new__(
            cls,
            *_args,
            supported=supported,
            normalizationRepository=normalizationRepository,
            normalizationTag=normalizationTag,
            normalizationIntegrationType=normalizationIntegrationType,
            _configuration=_configuration,
        )
