# coding: utf-8

"""
    Airbyte Configuration API

    Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Authentication (OSS): * When authenticating to the Configuration API, you must use Basic Authentication by setting the Authentication Header to Basic and base64 encoding the username and password (which are `airbyte` and `password` by default - so base64 encoding `airbyte:password` results in `YWlyYnl0ZTpwYXNzd29yZA==`). So the full header reads `'Authorization': \"Basic YWlyYnl0ZTpwYXNzd29yZA==\"`   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: contact@airbyte.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from airbyte_config_api_client import schemas  # noqa: F401


class OAuthConfigSpecification(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            oauthUserInputFromConnectorConfigSpecification = schemas.AnyTypeSchema
            completeOAuthOutputSpecification = schemas.AnyTypeSchema
            completeOAuthServerInputSpecification = schemas.AnyTypeSchema
            completeOAuthServerOutputSpecification = schemas.AnyTypeSchema
            __annotations__ = {
                "oauthUserInputFromConnectorConfigSpecification": oauthUserInputFromConnectorConfigSpecification,
                "completeOAuthOutputSpecification": completeOAuthOutputSpecification,
                "completeOAuthServerInputSpecification": completeOAuthServerInputSpecification,
                "completeOAuthServerOutputSpecification": completeOAuthServerOutputSpecification,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["oauthUserInputFromConnectorConfigSpecification"]) -> MetaOapg.properties.oauthUserInputFromConnectorConfigSpecification: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["completeOAuthOutputSpecification"]) -> MetaOapg.properties.completeOAuthOutputSpecification: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["completeOAuthServerInputSpecification"]) -> MetaOapg.properties.completeOAuthServerInputSpecification: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["completeOAuthServerOutputSpecification"]) -> MetaOapg.properties.completeOAuthServerOutputSpecification: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["oauthUserInputFromConnectorConfigSpecification", "completeOAuthOutputSpecification", "completeOAuthServerInputSpecification", "completeOAuthServerOutputSpecification", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["oauthUserInputFromConnectorConfigSpecification"]) -> typing.Union[MetaOapg.properties.oauthUserInputFromConnectorConfigSpecification, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["completeOAuthOutputSpecification"]) -> typing.Union[MetaOapg.properties.completeOAuthOutputSpecification, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["completeOAuthServerInputSpecification"]) -> typing.Union[MetaOapg.properties.completeOAuthServerInputSpecification, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["completeOAuthServerOutputSpecification"]) -> typing.Union[MetaOapg.properties.completeOAuthServerOutputSpecification, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["oauthUserInputFromConnectorConfigSpecification", "completeOAuthOutputSpecification", "completeOAuthServerInputSpecification", "completeOAuthServerOutputSpecification", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        oauthUserInputFromConnectorConfigSpecification: typing.Union[MetaOapg.properties.oauthUserInputFromConnectorConfigSpecification, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        completeOAuthOutputSpecification: typing.Union[MetaOapg.properties.completeOAuthOutputSpecification, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        completeOAuthServerInputSpecification: typing.Union[MetaOapg.properties.completeOAuthServerInputSpecification, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        completeOAuthServerOutputSpecification: typing.Union[MetaOapg.properties.completeOAuthServerOutputSpecification, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'OAuthConfigSpecification':
        return super().__new__(
            cls,
            *_args,
            oauthUserInputFromConnectorConfigSpecification=oauthUserInputFromConnectorConfigSpecification,
            completeOAuthOutputSpecification=completeOAuthOutputSpecification,
            completeOAuthServerInputSpecification=completeOAuthServerInputSpecification,
            completeOAuthServerOutputSpecification=completeOAuthServerOutputSpecification,
            _configuration=_configuration,
            **kwargs,
        )
