# coding: utf-8

"""
    Airbyte Configuration API

    Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Authentication (OSS): * When authenticating to the Configuration API, you must use Basic Authentication by setting the Authentication Header to Basic and base64 encoding the username and password (which are `airbyte` and `password` by default - so base64 encoding `airbyte:password` results in `YWlyYnl0ZTpwYXNzd29yZA==`). So the full header reads `'Authorization': \"Basic YWlyYnl0ZTpwYXNzd29yZA==\"`   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: contact@airbyte.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from airbyte_config_api_client import schemas  # noqa: F401


class ResourceRequirements(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    optional resource requirements to run workers (blank for unbounded allocations)
    """


    class MetaOapg:
        
        class properties:
            cpu_request = schemas.StrSchema
            cpu_limit = schemas.StrSchema
            memory_request = schemas.StrSchema
            memory_limit = schemas.StrSchema
            __annotations__ = {
                "cpu_request": cpu_request,
                "cpu_limit": cpu_limit,
                "memory_request": memory_request,
                "memory_limit": memory_limit,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cpu_request"]) -> MetaOapg.properties.cpu_request: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cpu_limit"]) -> MetaOapg.properties.cpu_limit: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["memory_request"]) -> MetaOapg.properties.memory_request: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["memory_limit"]) -> MetaOapg.properties.memory_limit: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["cpu_request", "cpu_limit", "memory_request", "memory_limit", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cpu_request"]) -> typing.Union[MetaOapg.properties.cpu_request, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cpu_limit"]) -> typing.Union[MetaOapg.properties.cpu_limit, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["memory_request"]) -> typing.Union[MetaOapg.properties.memory_request, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["memory_limit"]) -> typing.Union[MetaOapg.properties.memory_limit, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["cpu_request", "cpu_limit", "memory_request", "memory_limit", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        cpu_request: typing.Union[MetaOapg.properties.cpu_request, str, schemas.Unset] = schemas.unset,
        cpu_limit: typing.Union[MetaOapg.properties.cpu_limit, str, schemas.Unset] = schemas.unset,
        memory_request: typing.Union[MetaOapg.properties.memory_request, str, schemas.Unset] = schemas.unset,
        memory_limit: typing.Union[MetaOapg.properties.memory_limit, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ResourceRequirements':
        return super().__new__(
            cls,
            *_args,
            cpu_request=cpu_request,
            cpu_limit=cpu_limit,
            memory_request=memory_request,
            memory_limit=memory_limit,
            _configuration=_configuration,
            **kwargs,
        )
