# coding: utf-8

"""
    Airbyte Configuration API

    Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Authentication (OSS): * When authenticating to the Configuration API, you must use Basic Authentication by setting the Authentication Header to Basic and base64 encoding the username and password (which are `airbyte` and `password` by default - so base64 encoding `airbyte:password` results in `YWlyYnl0ZTpwYXNzd29yZA==`). So the full header reads `'Authorization': \"Basic YWlyYnl0ZTpwYXNzd29yZA==\"`   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: contact@airbyte.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from airbyte_config_api_client import schemas  # noqa: F401


class WebBackendConnectionRead(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "sourceId",
            "notifySchemaChanges",
            "destination",
            "name",
            "syncCatalog",
            "connectionId",
            "isSyncing",
            "source",
            "destinationId",
            "nonBreakingChangesPreference",
            "schemaChange",
            "status",
        }
        
        class properties:
            connectionId = schemas.UUIDSchema
            name = schemas.StrSchema
            sourceId = schemas.UUIDSchema
            destinationId = schemas.UUIDSchema
        
            @staticmethod
            def syncCatalog() -> typing.Type['AirbyteCatalog']:
                return AirbyteCatalog
        
            @staticmethod
            def status() -> typing.Type['ConnectionStatus']:
                return ConnectionStatus
        
            @staticmethod
            def source() -> typing.Type['SourceRead']:
                return SourceRead
        
            @staticmethod
            def destination() -> typing.Type['DestinationRead']:
                return DestinationRead
            isSyncing = schemas.BoolSchema
        
            @staticmethod
            def schemaChange() -> typing.Type['SchemaChange']:
                return SchemaChange
            notifySchemaChanges = schemas.BoolSchema
        
            @staticmethod
            def nonBreakingChangesPreference() -> typing.Type['NonBreakingChangesPreference']:
                return NonBreakingChangesPreference
        
            @staticmethod
            def namespaceDefinition() -> typing.Type['NamespaceDefinitionType']:
                return NamespaceDefinitionType
            namespaceFormat = schemas.StrSchema
            prefix = schemas.StrSchema
        
            @staticmethod
            def schedule() -> typing.Type['ConnectionSchedule']:
                return ConnectionSchedule
        
            @staticmethod
            def scheduleType() -> typing.Type['ConnectionScheduleType']:
                return ConnectionScheduleType
        
            @staticmethod
            def scheduleData() -> typing.Type['ConnectionScheduleData']:
                return ConnectionScheduleData
            
            
            class operationIds(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.UUIDSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, uuid.UUID, ]], typing.List[typing.Union[MetaOapg.items, str, uuid.UUID, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'operationIds':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            
            
            class operations(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['OperationRead']:
                        return OperationRead
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['OperationRead'], typing.List['OperationRead']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'operations':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'OperationRead':
                    return super().__getitem__(i)
            latestSyncJobCreatedAt = schemas.Int64Schema
        
            @staticmethod
            def latestSyncJobStatus() -> typing.Type['JobStatus']:
                return JobStatus
        
            @staticmethod
            def resourceRequirements() -> typing.Type['ResourceRequirements']:
                return ResourceRequirements
            catalogId = schemas.UUIDSchema
        
            @staticmethod
            def catalogDiff() -> typing.Type['CatalogDiff']:
                return CatalogDiff
        
            @staticmethod
            def geography() -> typing.Type['Geography']:
                return Geography
            __annotations__ = {
                "connectionId": connectionId,
                "name": name,
                "sourceId": sourceId,
                "destinationId": destinationId,
                "syncCatalog": syncCatalog,
                "status": status,
                "source": source,
                "destination": destination,
                "isSyncing": isSyncing,
                "schemaChange": schemaChange,
                "notifySchemaChanges": notifySchemaChanges,
                "nonBreakingChangesPreference": nonBreakingChangesPreference,
                "namespaceDefinition": namespaceDefinition,
                "namespaceFormat": namespaceFormat,
                "prefix": prefix,
                "schedule": schedule,
                "scheduleType": scheduleType,
                "scheduleData": scheduleData,
                "operationIds": operationIds,
                "operations": operations,
                "latestSyncJobCreatedAt": latestSyncJobCreatedAt,
                "latestSyncJobStatus": latestSyncJobStatus,
                "resourceRequirements": resourceRequirements,
                "catalogId": catalogId,
                "catalogDiff": catalogDiff,
                "geography": geography,
            }
    
    sourceId: MetaOapg.properties.sourceId
    notifySchemaChanges: MetaOapg.properties.notifySchemaChanges
    destination: 'DestinationRead'
    name: MetaOapg.properties.name
    syncCatalog: 'AirbyteCatalog'
    connectionId: MetaOapg.properties.connectionId
    isSyncing: MetaOapg.properties.isSyncing
    source: 'SourceRead'
    destinationId: MetaOapg.properties.destinationId
    nonBreakingChangesPreference: 'NonBreakingChangesPreference'
    schemaChange: 'SchemaChange'
    status: 'ConnectionStatus'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["connectionId"]) -> MetaOapg.properties.connectionId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sourceId"]) -> MetaOapg.properties.sourceId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["destinationId"]) -> MetaOapg.properties.destinationId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["syncCatalog"]) -> 'AirbyteCatalog': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> 'ConnectionStatus': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["source"]) -> 'SourceRead': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["destination"]) -> 'DestinationRead': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["isSyncing"]) -> MetaOapg.properties.isSyncing: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["schemaChange"]) -> 'SchemaChange': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["notifySchemaChanges"]) -> MetaOapg.properties.notifySchemaChanges: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["nonBreakingChangesPreference"]) -> 'NonBreakingChangesPreference': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["namespaceDefinition"]) -> 'NamespaceDefinitionType': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["namespaceFormat"]) -> MetaOapg.properties.namespaceFormat: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["prefix"]) -> MetaOapg.properties.prefix: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["schedule"]) -> 'ConnectionSchedule': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["scheduleType"]) -> 'ConnectionScheduleType': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["scheduleData"]) -> 'ConnectionScheduleData': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["operationIds"]) -> MetaOapg.properties.operationIds: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["operations"]) -> MetaOapg.properties.operations: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["latestSyncJobCreatedAt"]) -> MetaOapg.properties.latestSyncJobCreatedAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["latestSyncJobStatus"]) -> 'JobStatus': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["resourceRequirements"]) -> 'ResourceRequirements': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["catalogId"]) -> MetaOapg.properties.catalogId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["catalogDiff"]) -> 'CatalogDiff': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["geography"]) -> 'Geography': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["connectionId", "name", "sourceId", "destinationId", "syncCatalog", "status", "source", "destination", "isSyncing", "schemaChange", "notifySchemaChanges", "nonBreakingChangesPreference", "namespaceDefinition", "namespaceFormat", "prefix", "schedule", "scheduleType", "scheduleData", "operationIds", "operations", "latestSyncJobCreatedAt", "latestSyncJobStatus", "resourceRequirements", "catalogId", "catalogDiff", "geography", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["connectionId"]) -> MetaOapg.properties.connectionId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sourceId"]) -> MetaOapg.properties.sourceId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["destinationId"]) -> MetaOapg.properties.destinationId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["syncCatalog"]) -> 'AirbyteCatalog': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> 'ConnectionStatus': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["source"]) -> 'SourceRead': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["destination"]) -> 'DestinationRead': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["isSyncing"]) -> MetaOapg.properties.isSyncing: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["schemaChange"]) -> 'SchemaChange': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["notifySchemaChanges"]) -> MetaOapg.properties.notifySchemaChanges: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["nonBreakingChangesPreference"]) -> 'NonBreakingChangesPreference': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["namespaceDefinition"]) -> typing.Union['NamespaceDefinitionType', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["namespaceFormat"]) -> typing.Union[MetaOapg.properties.namespaceFormat, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["prefix"]) -> typing.Union[MetaOapg.properties.prefix, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["schedule"]) -> typing.Union['ConnectionSchedule', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["scheduleType"]) -> typing.Union['ConnectionScheduleType', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["scheduleData"]) -> typing.Union['ConnectionScheduleData', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["operationIds"]) -> typing.Union[MetaOapg.properties.operationIds, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["operations"]) -> typing.Union[MetaOapg.properties.operations, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["latestSyncJobCreatedAt"]) -> typing.Union[MetaOapg.properties.latestSyncJobCreatedAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["latestSyncJobStatus"]) -> typing.Union['JobStatus', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["resourceRequirements"]) -> typing.Union['ResourceRequirements', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["catalogId"]) -> typing.Union[MetaOapg.properties.catalogId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["catalogDiff"]) -> typing.Union['CatalogDiff', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["geography"]) -> typing.Union['Geography', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["connectionId", "name", "sourceId", "destinationId", "syncCatalog", "status", "source", "destination", "isSyncing", "schemaChange", "notifySchemaChanges", "nonBreakingChangesPreference", "namespaceDefinition", "namespaceFormat", "prefix", "schedule", "scheduleType", "scheduleData", "operationIds", "operations", "latestSyncJobCreatedAt", "latestSyncJobStatus", "resourceRequirements", "catalogId", "catalogDiff", "geography", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        sourceId: typing.Union[MetaOapg.properties.sourceId, str, uuid.UUID, ],
        notifySchemaChanges: typing.Union[MetaOapg.properties.notifySchemaChanges, bool, ],
        destination: 'DestinationRead',
        name: typing.Union[MetaOapg.properties.name, str, ],
        syncCatalog: 'AirbyteCatalog',
        connectionId: typing.Union[MetaOapg.properties.connectionId, str, uuid.UUID, ],
        isSyncing: typing.Union[MetaOapg.properties.isSyncing, bool, ],
        source: 'SourceRead',
        destinationId: typing.Union[MetaOapg.properties.destinationId, str, uuid.UUID, ],
        nonBreakingChangesPreference: 'NonBreakingChangesPreference',
        schemaChange: 'SchemaChange',
        status: 'ConnectionStatus',
        namespaceDefinition: typing.Union['NamespaceDefinitionType', schemas.Unset] = schemas.unset,
        namespaceFormat: typing.Union[MetaOapg.properties.namespaceFormat, str, schemas.Unset] = schemas.unset,
        prefix: typing.Union[MetaOapg.properties.prefix, str, schemas.Unset] = schemas.unset,
        schedule: typing.Union['ConnectionSchedule', schemas.Unset] = schemas.unset,
        scheduleType: typing.Union['ConnectionScheduleType', schemas.Unset] = schemas.unset,
        scheduleData: typing.Union['ConnectionScheduleData', schemas.Unset] = schemas.unset,
        operationIds: typing.Union[MetaOapg.properties.operationIds, list, tuple, schemas.Unset] = schemas.unset,
        operations: typing.Union[MetaOapg.properties.operations, list, tuple, schemas.Unset] = schemas.unset,
        latestSyncJobCreatedAt: typing.Union[MetaOapg.properties.latestSyncJobCreatedAt, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        latestSyncJobStatus: typing.Union['JobStatus', schemas.Unset] = schemas.unset,
        resourceRequirements: typing.Union['ResourceRequirements', schemas.Unset] = schemas.unset,
        catalogId: typing.Union[MetaOapg.properties.catalogId, str, uuid.UUID, schemas.Unset] = schemas.unset,
        catalogDiff: typing.Union['CatalogDiff', schemas.Unset] = schemas.unset,
        geography: typing.Union['Geography', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'WebBackendConnectionRead':
        return super().__new__(
            cls,
            *_args,
            sourceId=sourceId,
            notifySchemaChanges=notifySchemaChanges,
            destination=destination,
            name=name,
            syncCatalog=syncCatalog,
            connectionId=connectionId,
            isSyncing=isSyncing,
            source=source,
            destinationId=destinationId,
            nonBreakingChangesPreference=nonBreakingChangesPreference,
            schemaChange=schemaChange,
            status=status,
            namespaceDefinition=namespaceDefinition,
            namespaceFormat=namespaceFormat,
            prefix=prefix,
            schedule=schedule,
            scheduleType=scheduleType,
            scheduleData=scheduleData,
            operationIds=operationIds,
            operations=operations,
            latestSyncJobCreatedAt=latestSyncJobCreatedAt,
            latestSyncJobStatus=latestSyncJobStatus,
            resourceRequirements=resourceRequirements,
            catalogId=catalogId,
            catalogDiff=catalogDiff,
            geography=geography,
            _configuration=_configuration,
            **kwargs,
        )

from airbyte_config_api_client.model.airbyte_catalog import AirbyteCatalog
from airbyte_config_api_client.model.catalog_diff import CatalogDiff
from airbyte_config_api_client.model.connection_schedule import ConnectionSchedule
from airbyte_config_api_client.model.connection_schedule_data import ConnectionScheduleData
from airbyte_config_api_client.model.connection_schedule_type import ConnectionScheduleType
from airbyte_config_api_client.model.connection_status import ConnectionStatus
from airbyte_config_api_client.model.destination_read import DestinationRead
from airbyte_config_api_client.model.geography import Geography
from airbyte_config_api_client.model.job_status import JobStatus
from airbyte_config_api_client.model.namespace_definition_type import NamespaceDefinitionType
from airbyte_config_api_client.model.non_breaking_changes_preference import NonBreakingChangesPreference
from airbyte_config_api_client.model.operation_read import OperationRead
from airbyte_config_api_client.model.resource_requirements import ResourceRequirements
from airbyte_config_api_client.model.schema_change import SchemaChange
from airbyte_config_api_client.model.source_read import SourceRead
