# coding: utf-8

"""
    Airbyte Configuration API

    Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Authentication (OSS): * When authenticating to the Configuration API, you must use Basic Authentication by setting the Authentication Header to Basic and base64 encoding the username and password (which are `airbyte` and `password` by default - so base64 encoding `airbyte:password` results in `YWlyYnl0ZTpwYXNzd29yZA==`). So the full header reads `'Authorization': \"Basic YWlyYnl0ZTpwYXNzd29yZA==\"`   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: contact@airbyte.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from airbyte_config_api_client import schemas  # noqa: F401


class WorkspaceRead(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "initialSetupComplete",
            "customerId",
            "name",
            "slug",
            "workspaceId",
        }
        
        class properties:
            workspaceId = schemas.UUIDSchema
            customerId = schemas.UUIDSchema
            name = schemas.StrSchema
            slug = schemas.StrSchema
            initialSetupComplete = schemas.BoolSchema
            email = schemas.StrSchema
            displaySetupWizard = schemas.BoolSchema
            anonymousDataCollection = schemas.BoolSchema
            news = schemas.BoolSchema
            securityUpdates = schemas.BoolSchema
            
            
            class notifications(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['Notification']:
                        return Notification
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['Notification'], typing.List['Notification']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'notifications':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'Notification':
                    return super().__getitem__(i)
            firstCompletedSync = schemas.BoolSchema
            feedbackDone = schemas.BoolSchema
        
            @staticmethod
            def defaultGeography() -> typing.Type['Geography']:
                return Geography
            
            
            class webhookConfigs(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['WebhookConfigRead']:
                        return WebhookConfigRead
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['WebhookConfigRead'], typing.List['WebhookConfigRead']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'webhookConfigs':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'WebhookConfigRead':
                    return super().__getitem__(i)
            __annotations__ = {
                "workspaceId": workspaceId,
                "customerId": customerId,
                "name": name,
                "slug": slug,
                "initialSetupComplete": initialSetupComplete,
                "email": email,
                "displaySetupWizard": displaySetupWizard,
                "anonymousDataCollection": anonymousDataCollection,
                "news": news,
                "securityUpdates": securityUpdates,
                "notifications": notifications,
                "firstCompletedSync": firstCompletedSync,
                "feedbackDone": feedbackDone,
                "defaultGeography": defaultGeography,
                "webhookConfigs": webhookConfigs,
            }
    
    initialSetupComplete: MetaOapg.properties.initialSetupComplete
    customerId: MetaOapg.properties.customerId
    name: MetaOapg.properties.name
    slug: MetaOapg.properties.slug
    workspaceId: MetaOapg.properties.workspaceId
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["workspaceId"]) -> MetaOapg.properties.workspaceId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["customerId"]) -> MetaOapg.properties.customerId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["slug"]) -> MetaOapg.properties.slug: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["initialSetupComplete"]) -> MetaOapg.properties.initialSetupComplete: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["email"]) -> MetaOapg.properties.email: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["displaySetupWizard"]) -> MetaOapg.properties.displaySetupWizard: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["anonymousDataCollection"]) -> MetaOapg.properties.anonymousDataCollection: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["news"]) -> MetaOapg.properties.news: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["securityUpdates"]) -> MetaOapg.properties.securityUpdates: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["notifications"]) -> MetaOapg.properties.notifications: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["firstCompletedSync"]) -> MetaOapg.properties.firstCompletedSync: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["feedbackDone"]) -> MetaOapg.properties.feedbackDone: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["defaultGeography"]) -> 'Geography': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["webhookConfigs"]) -> MetaOapg.properties.webhookConfigs: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["workspaceId", "customerId", "name", "slug", "initialSetupComplete", "email", "displaySetupWizard", "anonymousDataCollection", "news", "securityUpdates", "notifications", "firstCompletedSync", "feedbackDone", "defaultGeography", "webhookConfigs", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["workspaceId"]) -> MetaOapg.properties.workspaceId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["customerId"]) -> MetaOapg.properties.customerId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["slug"]) -> MetaOapg.properties.slug: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["initialSetupComplete"]) -> MetaOapg.properties.initialSetupComplete: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["email"]) -> typing.Union[MetaOapg.properties.email, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["displaySetupWizard"]) -> typing.Union[MetaOapg.properties.displaySetupWizard, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["anonymousDataCollection"]) -> typing.Union[MetaOapg.properties.anonymousDataCollection, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["news"]) -> typing.Union[MetaOapg.properties.news, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["securityUpdates"]) -> typing.Union[MetaOapg.properties.securityUpdates, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["notifications"]) -> typing.Union[MetaOapg.properties.notifications, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["firstCompletedSync"]) -> typing.Union[MetaOapg.properties.firstCompletedSync, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["feedbackDone"]) -> typing.Union[MetaOapg.properties.feedbackDone, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["defaultGeography"]) -> typing.Union['Geography', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["webhookConfigs"]) -> typing.Union[MetaOapg.properties.webhookConfigs, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["workspaceId", "customerId", "name", "slug", "initialSetupComplete", "email", "displaySetupWizard", "anonymousDataCollection", "news", "securityUpdates", "notifications", "firstCompletedSync", "feedbackDone", "defaultGeography", "webhookConfigs", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        initialSetupComplete: typing.Union[MetaOapg.properties.initialSetupComplete, bool, ],
        customerId: typing.Union[MetaOapg.properties.customerId, str, uuid.UUID, ],
        name: typing.Union[MetaOapg.properties.name, str, ],
        slug: typing.Union[MetaOapg.properties.slug, str, ],
        workspaceId: typing.Union[MetaOapg.properties.workspaceId, str, uuid.UUID, ],
        email: typing.Union[MetaOapg.properties.email, str, schemas.Unset] = schemas.unset,
        displaySetupWizard: typing.Union[MetaOapg.properties.displaySetupWizard, bool, schemas.Unset] = schemas.unset,
        anonymousDataCollection: typing.Union[MetaOapg.properties.anonymousDataCollection, bool, schemas.Unset] = schemas.unset,
        news: typing.Union[MetaOapg.properties.news, bool, schemas.Unset] = schemas.unset,
        securityUpdates: typing.Union[MetaOapg.properties.securityUpdates, bool, schemas.Unset] = schemas.unset,
        notifications: typing.Union[MetaOapg.properties.notifications, list, tuple, schemas.Unset] = schemas.unset,
        firstCompletedSync: typing.Union[MetaOapg.properties.firstCompletedSync, bool, schemas.Unset] = schemas.unset,
        feedbackDone: typing.Union[MetaOapg.properties.feedbackDone, bool, schemas.Unset] = schemas.unset,
        defaultGeography: typing.Union['Geography', schemas.Unset] = schemas.unset,
        webhookConfigs: typing.Union[MetaOapg.properties.webhookConfigs, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'WorkspaceRead':
        return super().__new__(
            cls,
            *_args,
            initialSetupComplete=initialSetupComplete,
            customerId=customerId,
            name=name,
            slug=slug,
            workspaceId=workspaceId,
            email=email,
            displaySetupWizard=displaySetupWizard,
            anonymousDataCollection=anonymousDataCollection,
            news=news,
            securityUpdates=securityUpdates,
            notifications=notifications,
            firstCompletedSync=firstCompletedSync,
            feedbackDone=feedbackDone,
            defaultGeography=defaultGeography,
            webhookConfigs=webhookConfigs,
            _configuration=_configuration,
            **kwargs,
        )

from airbyte_config_api_client.model.geography import Geography
from airbyte_config_api_client.model.notification import Notification
from airbyte_config_api_client.model.webhook_config_read import WebhookConfigRead
