# coding: utf-8

"""
    Airbyte Configuration API

    Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Authentication (OSS): * When authenticating to the Configuration API, you must use Basic Authentication by setting the Authentication Header to Basic and base64 encoding the username and password (which are `airbyte` and `password` by default - so base64 encoding `airbyte:password` results in `YWlyYnl0ZTpwYXNzd29yZA==`). So the full header reads `'Authorization': \"Basic YWlyYnl0ZTpwYXNzd29yZA==\"`   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: contact@airbyte.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from airbyte_config_api_client import schemas  # noqa: F401


class WorkspaceCreate(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "name",
        }
        
        class properties:
            name = schemas.StrSchema
            email = schemas.StrSchema
            anonymousDataCollection = schemas.BoolSchema
            news = schemas.BoolSchema
            securityUpdates = schemas.BoolSchema
            
            
            class notifications(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['Notification']:
                        return Notification
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['Notification'], typing.List['Notification']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'notifications':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'Notification':
                    return super().__getitem__(i)
            displaySetupWizard = schemas.BoolSchema
        
            @staticmethod
            def defaultGeography() -> typing.Type['Geography']:
                return Geography
            
            
            class webhookConfigs(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['WebhookConfigWrite']:
                        return WebhookConfigWrite
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['WebhookConfigWrite'], typing.List['WebhookConfigWrite']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'webhookConfigs':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'WebhookConfigWrite':
                    return super().__getitem__(i)
            __annotations__ = {
                "name": name,
                "email": email,
                "anonymousDataCollection": anonymousDataCollection,
                "news": news,
                "securityUpdates": securityUpdates,
                "notifications": notifications,
                "displaySetupWizard": displaySetupWizard,
                "defaultGeography": defaultGeography,
                "webhookConfigs": webhookConfigs,
            }
    
    name: MetaOapg.properties.name
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["email"]) -> MetaOapg.properties.email: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["anonymousDataCollection"]) -> MetaOapg.properties.anonymousDataCollection: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["news"]) -> MetaOapg.properties.news: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["securityUpdates"]) -> MetaOapg.properties.securityUpdates: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["notifications"]) -> MetaOapg.properties.notifications: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["displaySetupWizard"]) -> MetaOapg.properties.displaySetupWizard: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["defaultGeography"]) -> 'Geography': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["webhookConfigs"]) -> MetaOapg.properties.webhookConfigs: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["name", "email", "anonymousDataCollection", "news", "securityUpdates", "notifications", "displaySetupWizard", "defaultGeography", "webhookConfigs", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["email"]) -> typing.Union[MetaOapg.properties.email, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["anonymousDataCollection"]) -> typing.Union[MetaOapg.properties.anonymousDataCollection, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["news"]) -> typing.Union[MetaOapg.properties.news, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["securityUpdates"]) -> typing.Union[MetaOapg.properties.securityUpdates, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["notifications"]) -> typing.Union[MetaOapg.properties.notifications, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["displaySetupWizard"]) -> typing.Union[MetaOapg.properties.displaySetupWizard, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["defaultGeography"]) -> typing.Union['Geography', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["webhookConfigs"]) -> typing.Union[MetaOapg.properties.webhookConfigs, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["name", "email", "anonymousDataCollection", "news", "securityUpdates", "notifications", "displaySetupWizard", "defaultGeography", "webhookConfigs", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        name: typing.Union[MetaOapg.properties.name, str, ],
        email: typing.Union[MetaOapg.properties.email, str, schemas.Unset] = schemas.unset,
        anonymousDataCollection: typing.Union[MetaOapg.properties.anonymousDataCollection, bool, schemas.Unset] = schemas.unset,
        news: typing.Union[MetaOapg.properties.news, bool, schemas.Unset] = schemas.unset,
        securityUpdates: typing.Union[MetaOapg.properties.securityUpdates, bool, schemas.Unset] = schemas.unset,
        notifications: typing.Union[MetaOapg.properties.notifications, list, tuple, schemas.Unset] = schemas.unset,
        displaySetupWizard: typing.Union[MetaOapg.properties.displaySetupWizard, bool, schemas.Unset] = schemas.unset,
        defaultGeography: typing.Union['Geography', schemas.Unset] = schemas.unset,
        webhookConfigs: typing.Union[MetaOapg.properties.webhookConfigs, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'WorkspaceCreate':
        return super().__new__(
            cls,
            *_args,
            name=name,
            email=email,
            anonymousDataCollection=anonymousDataCollection,
            news=news,
            securityUpdates=securityUpdates,
            notifications=notifications,
            displaySetupWizard=displaySetupWizard,
            defaultGeography=defaultGeography,
            webhookConfigs=webhookConfigs,
            _configuration=_configuration,
            **kwargs,
        )

from airbyte_config_api_client.model.geography import Geography
from airbyte_config_api_client.model.notification import Notification
from airbyte_config_api_client.model.webhook_config_write import WebhookConfigWrite
