# coding: utf-8

"""
    Airbyte Configuration API

    Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Authentication (OSS): * When authenticating to the Configuration API, you must use Basic Authentication by setting the Authentication Header to Basic and base64 encoding the username and password (which are `airbyte` and `password` by default - so base64 encoding `airbyte:password` results in `YWlyYnl0ZTpwYXNzd29yZA==`). So the full header reads `'Authorization': \"Basic YWlyYnl0ZTpwYXNzd29yZA==\"`   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: contact@airbyte.io
    Generated by: https://openapi-generator.tech
"""

from airbyte_config_api_client.paths.v1_source_definitions_create_custom.post import CreateCustomSourceDefinition
from airbyte_config_api_client.paths.v1_source_definitions_delete.post import DeleteSourceDefinition
from airbyte_config_api_client.paths.v1_source_definitions_get.post import GetSourceDefinition
from airbyte_config_api_client.paths.v1_source_definitions_get_for_workspace.post import GetSourceDefinitionForWorkspace
from airbyte_config_api_client.paths.v1_source_definitions_grant_definition.post import GrantSourceDefinitionToWorkspace
from airbyte_config_api_client.paths.v1_source_definitions_list_latest.post import ListLatestSourceDefinitions
from airbyte_config_api_client.paths.v1_source_definitions_list_private.post import ListPrivateSourceDefinitions
from airbyte_config_api_client.paths.v1_source_definitions_list.post import ListSourceDefinitions
from airbyte_config_api_client.paths.v1_source_definitions_list_for_workspace.post import ListSourceDefinitionsForWorkspace
from airbyte_config_api_client.paths.v1_source_definitions_revoke_definition.post import RevokeSourceDefinitionFromWorkspace
from airbyte_config_api_client.paths.v1_source_definitions_update.post import UpdateSourceDefinition


class SourceDefinitionApi(
    CreateCustomSourceDefinition,
    DeleteSourceDefinition,
    GetSourceDefinition,
    GetSourceDefinitionForWorkspace,
    GrantSourceDefinitionToWorkspace,
    ListLatestSourceDefinitions,
    ListPrivateSourceDefinitions,
    ListSourceDefinitions,
    ListSourceDefinitionsForWorkspace,
    RevokeSourceDefinitionFromWorkspace,
    UpdateSourceDefinition,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
